#!/usr/bin/env python3
from guardiand.daemon import GuardianDaemon

def main():
    """ Runs guardiand """
    # TODO: add argument parser
    daemon = GuardianDaemon()
    daemon.run()

if __name__ == '__main__':
    main()
